before_install:
  - wget -O- http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
  - echo deb http://packages.couchbase.com/snapshot/ubuntu oneiric oneiric/main | sudo tee /etc/apt/sources.list.d/couchbase.list
  - sudo apt-get update
  - sudo apt-get -y install libevent-dev libvbucket-dev libcouchbase-dev

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
